version: '3.3'

services:

  postgres:
    image: postgres:16.1-alpine
    env_file: .env/dev.env
    ports:
      - "15432:5432"
    volumes:
      - pokestation-postgres-data:/var/lib/postgresql/data
      - ./db/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - pokestation-network
      
  pgadmin:
    image: dpage/pgadmin4:7.8
    env_file: .env/dev.env
    ports:
      - "16543:80"
    volumes:
      - ./conf/pgadmin/servers.json:/pgadmin4/servers.json
    restart: always
    networks:
      - pokestation-network
    depends_on:
      postgres:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    env_file: .env/dev.env
    ports:
      - "9090:8080"
      - "9443:8443"
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
    volumes:
      - ./conf/keycloak/import/:/opt/keycloak/data/import:ro
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 230s
    networks:
      - pokestation-network
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build: backend
    env_file: .env/dev.env
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./backend:/usr/src/app
    command: ["./mvnw", "spring-boot:run"]
    restart: always
    networks:
      - pokestation-network
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    extra_hosts:
        - "auth.pokestation.com:192.168.3.9" #host and ip

  nginx:
    image: nginx:1.25.3
    env_file: .env/dev.env
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pokestation-network
    depends_on:
      keycloak:
        condition: service_healthy
      backend:
        condition: service_started

  frontend:
    build: frontend
    env_file: .env/dev.env
    ports:
      - "7070:80"
      - "7443:443"
    restart: always
    networks:
      - pokestation-network
    depends_on:
      - backend

  # metabase:
  #   image: metabase/metabase:v0.36.7
  #   env_file: .env/prod.env
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - inova-cnj-metabase-data:/metabase-data
  #   environment:
  #     JAVA_TIMEZONE: America/Recife
  #     JAVA_TOOL_OPTIONS: -Xmx1g -Duser.country=BR -Duser.language=pt
  #   restart: always
  #   networks:
  #     - pokestation-network
  #   depends_on:
  #     - postgres

volumes:
  pokestation-postgres-data:
    driver: local

networks: 
  pokestation-network:
    driver: bridge
    attachable: true